#!/bin/bash

# Nasty Hack
setfacl --recursive --modify d:u:icinga:rwx,u:icinga2-user:rwx /etc/icinga2/

if [[ ${CONFIG_MODE} = "GIT" ]]; then
	# Check if GIT_REPOSITORY is set
	if [[ -n "${GIT_REPOSITORY}" ]]; then
		 echo "Configured Config At ${GIT_REPOSITORY}"
	else
		echo "No GIT Repository Configured"
		exit 1
	fi

	# Check if GIT_DEPLOY_KEY is set, If so, write to file
	if [[ -n "${GIT_IDENTITY_KEY}" ]]; then
		echo "Detected GIT DEPLOY KEY, Writing to /home/icinga2-user/.git_deploy_key"
		cp ${GIT_IDENTITY_KEY} /home/icinga2-user/.git_deploy_key
		chmod 600 /home/icinga2-user/.git_deploy_key
	else
		echo "No GIT IDENTITY KEY Configured"
		exit 1
	fi

	# Clone the Repoistory
	GIT_SSH_COMMAND='ssh -i /home/icinga2-user/.git_deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' git clone ${GIT_REPOSITORY} /etc/icinga2
fi

if [ "${CONFIG_MODE}" = "DISK" ]; then
	echo "CONFIG MODE DISK ACTIVATED"
	echo "COPYING FROM /config"
	cp -r /config /etc/icinga2
fi
